# Generated by Django 5.0.2 on 2025-10-03 16:36

# Importa utilidades de borrado para relaciones foraneas.
import django.db.models.deletion
# Trae la configuracion global del proyecto para acceder al modelo de usuario.
from django.conf import settings
# Carga las clases base de migraciones y tipos de campos de Django.
from django.db import migrations, models


class Migration(migrations.Migration):
    # Indica que esta es la primera migracion de la app.
    initial = True

    # Lista de dependencias que deben ejecutarse antes que esta migracion.
    dependencies = [
        # Permite que el modelo de usuario sea configurable (swappable).
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # Pasos que Django debe aplicar a la base de datos.
    operations = [
        migrations.CreateModel(
            # Nombre del modelo a crear en la base de datos.
            name='Profiles',
            # Define los campos de la nueva tabla.
            fields=[
                # Clave primaria autoincremental de 64 bits.
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                # Marca cuando se creo el registro por primera vez.
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                # Guarda el ultimo momento en que se actualizo (si aplica).
                ('update', models.DateTimeField(blank=True, null=True)),
                # Relacion al usuario dueno del perfil que se elimina en cascada.
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
