<<<<<<< HEAD
# Generated by Django 5.0.2 on 2025-10-16 08:13

# Habilita reglas de borrado en cascada para relaciones foraneas.
import django.db.models.deletion
# Obtiene el modelo de usuario configurable desde la configuracion global.
from django.conf import settings
# Importa las utilidades principales para definir migraciones y campos.
=======
# Generated by Django 5.0.2 on 2025-10-22 18:03

import django.db.models.deletion
from django.conf import settings
>>>>>>> upstream/master
from django.db import migrations, models


class Migration(migrations.Migration):
<<<<<<< HEAD
    # Esta migracion depende de la anterior y del modelo swappable de usuario.
=======

>>>>>>> upstream/master
    dependencies = [
        ('app_movil_escolar_api', '0002_administradores_delete_profiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

<<<<<<< HEAD
    # Conjunto de pasos que van a ejecutarse sobre la base de datos.
    operations = [
        migrations.CreateModel(
            # Define el modelo Alumnos.
            name='Alumnos',
            # Campos que integran la tabla de alumnos.
            fields=[
                # Identificador principal autoincremental.
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                # Telefono opcional del alumno.
                ('telefono', models.CharField(blank=True, max_length=255, null=True)),
                # Fecha de creacion del registro.
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                # Ultima fecha de actualizacion permitiendo nulos.
                ('update', models.DateTimeField(blank=True, null=True)),
                # Relacion al usuario asociado que se elimina en cascada.
=======
    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('matricula', models.CharField(blank=True, max_length=255, null=True)),
                ('curp', models.CharField(blank=True, max_length=255, null=True)),
                ('rfc', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_nacimiento', models.DateTimeField(blank=True, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=255, null=True)),
                ('ocupacion', models.CharField(blank=True, max_length=255, null=True)),
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(blank=True, null=True)),
>>>>>>> upstream/master
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            # Define el modelo Maestros.
            name='Maestros',
            # Campos para la tabla de maestros.
            fields=[
                # Identificador principal autoincremental.
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                # Telefono de contacto del maestro.
                ('telefono', models.CharField(blank=True, max_length=255, null=True)),
                # Fecha de creacion automatica del registro.
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                # Fecha opcional de ultima actualizacion.
                ('update', models.DateTimeField(blank=True, null=True)),
                # Relacion al usuario dueno del registro con borrado en cascada.
=======
            name='Maestros',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_trabajador', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_nacimiento', models.DateTimeField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=255, null=True)),
                ('rfc', models.CharField(blank=True, max_length=255, null=True)),
                ('cubiculo', models.CharField(blank=True, max_length=255, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('area_investigacion', models.CharField(blank=True, max_length=255, null=True)),
                ('materias_json', models.TextField(blank=True, null=True)),
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(blank=True, null=True)),
>>>>>>> upstream/master
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
