# Generated by Django 5.0.2 on 2025-10-17 06:56

# Importa el modulo de migraciones que provee operaciones de schema.
from django.db import migrations


class Migration(migrations.Migration):
    # Necesita que la migracion 0004 ya se haya aplicado.
    dependencies = [
        ('app_movil_escolar_api', '0004_alumnos_curp_alumnos_edad_alumnos_fecha_nacimiento_and_more'),
    ]

    # Operaciones concretas que se aplican en esta migracion.
    operations = [
        migrations.RemoveField(
            # Se modifica el modelo Maestros.
            model_name='maestros',
            # Se elimina el campo update porque dejo de ser necesario.
            name='update',
        ),
    ]
