# Generated by Django 5.0.2 on 2025-10-17 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_movil_escolar_api', '0004_alumnos_curp_alumnos_edad_alumnos_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maestros',
            name='update',
        ),
    ]
