# Generated by Django 5.0.2 on 2025-11-21 15:49

from django.db import migrations


def drop_maestros_edad(apps, schema_editor):
    Maestro = apps.get_model('app_movil_escolar_api', 'Maestros')
    table = Maestro._meta.db_table
    with schema_editor.connection.cursor() as cursor:
        cols = [col.name for col in schema_editor.connection.introspection.get_table_description(cursor, table)]
    if 'edad' in cols:
        schema_editor.execute(
            f"ALTER TABLE {schema_editor.quote_name(table)} "
            f"DROP COLUMN {schema_editor.quote_name('edad')}"
        )


def add_maestros_edad(apps, schema_editor):
    Maestro = apps.get_model('app_movil_escolar_api', 'Maestros')
    table = Maestro._meta.db_table
    with schema_editor.connection.cursor() as cursor:
        cols = [col.name for col in schema_editor.connection.introspection.get_table_description(cursor, table)]
    if 'edad' not in cols:
        schema_editor.execute(
            f"ALTER TABLE {schema_editor.quote_name(table)} "
            f"ADD COLUMN {schema_editor.quote_name('edad')} integer NULL"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('app_movil_escolar_api', '0006_maestros_update_alter_alumnos_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='maestros',
                    name='edad',
                ),
            ],
            database_operations=[
                migrations.RunPython(drop_maestros_edad, add_maestros_edad),
            ],
        ),
    ]
