# Generated by Django 5.0.2 on 2025-10-26 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sistema_escolar_api', '0003_estudiantes_maestros'),
    ]

    operations = [
        migrations.AddField(
            model_name='maestros',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
